apiVersion: v1
kind: Service
metadata:
  name: {{ template "deluge.fullname" . }}-daemon
  labels:
    app.kubernetes.io/name: {{ include "deluge.name" . }}
    helm.sh/chart: {{ include "deluge.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.daemonservice.labels }}
{{ toYaml .Values.daemonservice.labels | indent 4 }}
{{- end }}
{{- with .Values.daemonservice.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if (or (eq .Values.daemonservice.type "ClusterIP") (empty .Values.daemonservice.type)) }}
  type: ClusterIP
  {{- if .Values.daemonservice.clusterIP }}
  clusterIP: {{ .Values.daemonservice.clusterIP }}
  {{end}}
{{- else if eq .Values.daemonservice.type "LoadBalancer" }}
  type: {{ .Values.daemonservice.type }}
  {{- if .Values.daemonservice.loadBalancerIP }}
  loadBalancerIP: {{ .Values.daemonservice.loadBalancerIP }}
  {{- end }}
  {{- if .Values.daemonservice.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.daemonservice.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.daemonservice.type }}
{{- end }}
{{- if .Values.daemonservice.externalIPs }}
  externalIPs:
{{ toYaml .Values.daemonservice.externalIPs | indent 4 }}
{{- end }}
  {{- if .Values.daemonservice.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.daemonservice.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: daemon
      port: 58846
      protocol: TCP
      targetPort: daemon
{{ if (eq .Values.daemonservice.type "NodePort") }}
      nodePort: {{ default 30846 .Values.daemonservice.nodePort }}
{{ end }}
  selector:
    app.kubernetes.io/name: {{ include "deluge.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    