apiVersion: v1
description: Deluge is a Python BitTorrent client based on libtorrent
name: deluge
version: 1.1.1
keywords:
  - deluge
  - libtorrent
home: https://github.com/deluge-torrent/deluge
sources:
  - https://hub.docker.com/r/linuxserver/deluge/
dependencies: []
maintainers:
  - name: nikdoof
    email: andy@tensixtyone.com
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/deluge-icon.png
appVersion: 2.0.3-2201906121747ubuntu18.04.1-ls57
