apiVersion: v1
appVersion: "0.8.5"
description: Collect VMware vCenter and ESXi performance metrics and send them to InfluxDB
name: vsphere-influxdb-go
version: 0.2.0
keywords:
  - vsphere
  - influxdb
  - esx
home: https://github.com/Oxalide/vsphere-influxdb-go
sources:
  - https://hub.docker.com/r/nikdoof/vsphere-influxdb-go/
  - https://github.com/janeczku/calibre-web
maintainers:
  - name: nikdoof
    email: andy@tensixtyone.com
